In [2]:
import pandas as pd

In [3]:
books = pd.read_csv("../data/processed/books_with_genres.csv")
books["isbn13"] = books["isbn13"].astype(str)

In [4]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,dominant_emotion,emotion_score,display_genre
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,fear,0.654842,Fiction
1,9780002261982,0002261987,Spider's Web,"Charles Osborne, Agatha Christie",Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,fear,0.755521,Mystery
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,fear,0.939291,Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,anger,0.332783,Religion
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,neutral,0.854798,Fantasy

In [5]:
books["categories"].value_counts().head(100)

categories
Fiction                      2111
Juvenile Fiction              390
Biography & Autobiography     311
History                       207
Literary Criticism            124
                             ...
Australian fiction              2
Australia                       2
College teachers                2
Short stories, American         2
Horror tales                    2
Name: count, Length: 100, dtype: int64

In [6]:
genre_mapping = {

    # Fiction
    "Fiction": "Fiction",
    "Juvenile Fiction": "Children",
    "Young Adult Fiction": "Young Adult",

    # Biography
    "Biography & Autobiography": "Biography",

    # History
    "History": "History",

    # Literature
    "Literary Criticism": "Literature",
    "Poetry": "Literature",
    "Drama": "Literature",

    # Fantasy / Sci-Fi
    "Science Fiction": "Science Fiction",
    "Fantasy": "Fantasy",

    # Mystery
    "Detective and mystery stories": "Mystery",
    "Mystery": "Mystery",

    # Horror
    "Horror tales": "Horror",

    # Romance
    "Love stories": "Romance",

    # Religion
    "Religion": "Religion",
    "Christian life": "Religion",

    # Philosophy
    "Philosophy": "Philosophy",

    # Psychology
    "Psychology": "Psychology",

    # Business
    "Business & Economics": "Business",

    # Self Help
    "Self-Help": "Self Help",

    # Comics
    "Comics & Graphic Novels": "Comics",

    # Cooking
    "Cooking": "Cooking",

    # Travel
    "Travel": "Travel",

    # Science
    "Science": "Science"
}

In [7]:
books["display_genre"] = (
    books["categories"]
    .map(genre_mapping)
    .fillna("Other")
)

In [8]:
books["display_genre"].value_counts()

display_genre
Fiction        2111
Other          1301
Children        390
Biography       311
Literature      261
History         207
Religion        120
Philosophy      117
Comics          116
Science          56
Business         49
Cooking          35
Psychology       33
Travel           32
Self Help        28
Mystery          14
Young Adult       8
Fantasy           6
Horror            2
Name: count, dtype: int64

In [9]:
genre_mapping.update({

    # Children
    "Juvenile Nonfiction": "Children",

    # Literature
    "Literary Collections": "Literature",

    # Society
    "Social Science": "Social Science",

    # Arts
    "Performing Arts": "Arts",
    "Art": "Arts",
    "Architecture": "Arts",
    "Design": "Arts",
    "Music": "Arts",

    # Spirituality
    "Body, Mind & Spirit": "Spirituality",
    "Bible": "Religion",

    # Technology
    "Computers": "Technology",

    # Health
    "Health & Fitness": "Health",
    "Medical": "Health",

    # Education
    "Education": "Education",
    "Language Arts & Disciplines": "Education",
    "Foreign Language Study": "Education",

    # Politics & Law
    "Political Science": "Politics",
    "Law": "Law",

    # Sports
    "Sports & Recreation": "Sports",

    # Humor
    "Humor": "Humor",

    # Crime
    "True Crime": "Crime",

    # Science
    "Nature": "Science",
    "Mathematics": "Science",

    # Family
    "Family & Relationships": "Self Help"
})

In [10]:
books["display_genre"] = (
    books["categories"]
    .map(genre_mapping)
    .fillna("Other")
)

books["display_genre"].value_counts()

display_genre
Fiction           2111
Other              749
Children           447
Literature         311
Biography          311
History            207
Religion           122
Philosophy         117
Comics             116
Arts               102
Science             80
Self Help           55
Education           49
Business            49
Social Science      48
Health              47
Cooking             35
Psychology          33
Travel              32
Spirituality        32
Politics            30
Technology          28
Humor               23
Mystery             14
Sports              12
Crime               11
Law                 10
Young Adult          8
Fantasy              6
Horror               2
Name: count, dtype: int64

In [11]:
def assign_fantasy_genre(row):

    category = str(row["categories"]).lower()
    description = str(row["description"]).lower()

    fantasy_keywords = [
        "magic",
        "wizard",
        "witch",
        "dragon",
        "dragons",
        "spell",
        "sorcerer",
        "hogwarts",
        "elf",
        "elves",
        "dwarf",
        "orc",
        "kingdom",
        "fairy",
        "mythical",
        "quest"
    ]

    # Already Fantasy
    if category == "fantasy":
        return "Fantasy"

    # Description contains fantasy keywords
    if any(keyword in description for keyword in fantasy_keywords):
        return "Fantasy"

    return row["display_genre"]

In [12]:
books["display_genre"] = books.apply(
    assign_fantasy_genre,
    axis=1
)

In [13]:
books[
    books["title"].str.contains("Harry Potter", case=False, na=False)
][["title", "display_genre"]]

                                                  title display_genre
2097   Harry Potter and the Chamber of Secrets (Book 2)       Fantasy
2108  Harry Potter and the Order of the Phoenix (Boo...       Fantasy
2124            Harry Potter and the Chamber of Secrets       Fantasy
2125     Harry Potter and the Sorcerer's Stone (Book 1)       Fantasy
2134  Harry Potter and the Prisoner of Azkaban (Book 3)       Fantasy
2136                                       Harry Potter       Fantasy
2142    Harry Potter and the Half-Blood Prince (Book 6)       Fantasy
2149                        The Harry Potter Collection       Fantasy
3464                Harry Potter and the Goblet of Fire       Fantasy
3476           Harry Potter and the Prisoner of Azkaban       Fantasy
3536                        The Science of Harry Potter       Fantasy
3982                        Harry Potter and Philosophy       Fantasy
4290  Ultimate Unofficial Guide to the Mysteries of ...    Literature
4298  Unauthorized Harry Potter and the Deathly Hall...       Fantasy
4479                    Looking for God in Harry Potter    Literature

In [14]:
books.to_csv("../data/processed/books_with_genres.csv", index=False)

In [15]:
books["display_genre"].unique()

<StringArray>
[       'Fiction',        'Mystery',       'Religion',        'Fantasy',
          'Other',     'Literature',      'Biography',       'Children',
      'Education',        'History',       'Business',        'Science',
     'Philosophy',      'Self Help',          'Crime',     'Psychology',
         'Travel', 'Social Science',         'Health',         'Comics',
   'Spirituality',       'Politics',     'Technology',           'Arts',
         'Sports',        'Cooking',    'Young Adult',          'Humor',
            'Law']
Length: 29, dtype: str

In [16]:
books[books["title"].str.contains("Harry", case=False, na=False)][
    ["title", "categories", "display_genre"]
]

,title,categories,display_genre
1345,The Harry Bosch Novels,Fiction,Fiction
1359,"Harry Bosch Novels, The: Volume 2",Fiction,Fantasy
2097,Harry Potter and the Chamber of Secrets (Book 2),Juvenile Fiction,Fantasy
2108,Harry Potter and the Order of the Phoenix (Boo...,Juvenile Fiction,Fantasy
2124,Harry Potter and the Chamber of Secrets,Juvenile Fiction,Fantasy
2125,Harry Potter and the Sorcerer's Stone (Book 1),Juvenile Fiction,Fantasy
2134,Harry Potter and the Prisoner of Azkaban (Book 3),Juvenile Fiction,Fantasy
2136,Harry Potter,Juvenile Fiction,Fantasy
2142,Harry Potter and the Half-Blood Prince (Book 6),Juvenile Fiction,Fantasy
2149,The Harry Potter Collection,Juvenile Fiction,Fantasy
3464,Harry Potter and the Goblet of Fire,Juvenile Fiction,Fantasy
3476,Harry Potter and the Prisoner of Azkaban,England,Fantasy
3479,When Harry Met Sally,Man-woman relationships,Other
3536,The Science of Harry Potter,Magic,Fantasy
3982,Harry Potter and Philosophy,Fiction,Fantasy
4290,Ultimate Unofficial Guide to the Mysteries of ...,Literary Criticism,Literature
4298,Unauthorized Harry Potter and the Deathly Hall...,Fiction,Fantasy
4479,Looking for God in Harry Potter,Literary Criticism,Literature